### ISSUE TITLE
add app_ui to github repository!!

### ISSUE THREAD

**Issue by ibelarouci** [ghonijee/brapa-app#2]
add app_ui to github repository!!
the directory not exist in repository.
```
app_ui:
    path: ../app_ui
```

![image](https://github.com/ghonijee/brapa-app/assets/8080006/4b98cb9e-afb5-4ff5-8d71-b589bee77d58)

**Comment by ghonijee** [comment]
Hi @ibelarouci, you can clone from this repo

https://github.com/ghonijee/app-ui

I will update my pubspect ASAP.

thanks

**Comment by ibelarouci** [comment]
try to do this:?
```
app-ui:
    git:
      url: https://github.com/ghonijee/app-ui.git
      ref: master 
```
